# Generated by Django 4.0.5 on 2022-07-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieimage',
            old_name='image',
            new_name='images',
        ),
    ]
