# Generated by Django 4.0.5 on 2022-07-04 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_rename_image_movieimage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieimage',
            old_name='images',
            new_name='image',
        ),
    ]
