# Generated by Django 4.0.5 on 2022-07-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_rename_images_movieimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='Images/Toronto_image.jpg', null=True, upload_to='Images'),
        ),
    ]
