# Generated by Django 4.0.5 on 2022-07-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='images/Toronto_image.jpg', null=True, upload_to='images'),
        ),
    ]
